#include "ui/EditorUI.h"
#include <imgui.h>
#include <backends/imgui_impl_glfw.h>
#include <backends/imgui_impl_opengl3.h>
#include <GLFW/glfw3.h>
#include <string>

#include <imgui_internal.h> 

#include <filesystem>
#include <iostream> 
#include <fstream>


namespace fs = std::filesystem;

EditorUI::EditorUI() : window(nullptr) {}

EditorUI::~EditorUI() {
    Shutdown();
}
void EditorUI::Init(GLFWwindow* win){
    window = win;

    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO& io = ImGui::GetIO();

    io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;
    io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable;
    

    ImGui::StyleColorsDark();

    ImGui_ImplGlfw_InitForOpenGL(window, true);
    ImGui_ImplOpenGL3_Init("#version 330 core");
}


void EditorUI::NewFrame() {
    ImGui_ImplOpenGL3_NewFrame();
    ImGui_ImplGlfw_NewFrame();
    ImGui::NewFrame();
}


void EditorUI::Draw(){

    DrawMenuBar();
    SetupDockspace();
    DrawTextEditorPane();
    DrawConsolePane();
    //DrawViewportPane(); // for renderer
}


void EditorUI::SetupDockspace() {
    // the dockspace is a full screen window behind everything else
    const ImGuiViewport* viewport = ImGui::GetMainViewport();
    ImGui::SetNextWindowPos(viewport->WorkPos);
    ImGui::SetNextWindowSize(viewport->WorkSize);
    ImGui::SetNextWindowViewport(viewport->ID);

    ImGuiWindowFlags window_flags = ImGuiWindowFlags_NoDocking | ImGuiWindowFlags_NoTitleBar | 
                                    ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoResize | 
                                    ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoBringToFrontOnFocus | 
                                    ImGuiWindowFlags_NoNavFocus | ImGuiWindowFlags_NoBackground;

    ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0.0f, 0.0f));
    ImGui::Begin("MainDockSpaceWindow", nullptr, window_flags);
    ImGui::PopStyleVar();

    ImGuiID dockspace_id = ImGui::GetID("MyDockSpace");
    ImGui::DockSpace(dockspace_id, ImVec2(0.0f, 0.0f), ImGuiDockNodeFlags_None);

    // initial layout builder
    static bool layout_initialized = false;
    if (!layout_initialized) {
        layout_initialized = true;

        // clear any previous layout
        ImGui::DockBuilderRemoveNode(dockspace_id); 
        ImGui::DockBuilderAddNode(dockspace_id, ImGuiDockNodeFlags_DockSpace);
        ImGui::DockBuilderSetNodeSize(dockspace_id, viewport->WorkSize);

        // dock_main_id is the right side
        // dock_editor_id is the left side
        ImGuiID dock_main_id = dockspace_id;
        ImGuiID dock_editor_id = ImGui::DockBuilderSplitNode(dock_main_id, ImGuiDir_Left, 0.5f, nullptr, &dock_main_id);

        // map window names to the dock nodes
        ImGui::DockBuilderDockWindow("Code Editor", dock_editor_id);
        ImGui::DockBuilderDockWindow("Utility View", dock_main_id);
        
        ImGui::DockBuilderFinish(dockspace_id);
    }

    ImGui::End();
}

void EditorUI::LoadWorkspace(const std::string& directoryPath) {
    openDocuments.clear();

    // create the workspace directory if it doesn't exist yet
    if (!fs::exists(directoryPath)) {
        fs::create_directory(directoryPath);
        std::cout << "Created workspace directory: " << directoryPath << "\n";
        
        // autogenerated
        std::ofstream file(directoryPath + "/main.cpp");
        file << "class App {\npublic:\n    void update() {\n        // Your code here\n    }\n};\n";
        file.close();
        std::cout << "Generated starter file: main.cpp\n";
    }

    // iterate through all files in the directory
    for (const auto& entry : fs::directory_iterator(directoryPath)) {
        if (entry.is_regular_file()) {
            Document doc;
            doc.filename = entry.path().filename().string();
            doc.filepath = entry.path().string();

            // Read the file contents into a string
            std::ifstream file(doc.filepath, std::ios::binary);
            std::string content((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());

            // Initialize the syntax highlighter (C++ rules)
            doc.editor.SetLanguageDefinition(TextEditor::LanguageDefinition::CPlusPlus());
            
            // Push the file contents directly into the editor component
            doc.editor.SetText(content);
            
            doc.lastKnownText = content;

            // by default, the document is unmodified and open
            doc.isDirty = false;
            doc.isOpen = true;

            openDocuments.push_back(doc);
        }
    }
}
void EditorUI::DrawMenuBar() {

    if (ImGui::BeginMainMenuBar()) {
        if (ImGui::BeginMenu("File")) {
            if (ImGui::MenuItem("New")) {}
            if (ImGui::MenuItem("Save", "Ctrl+S")) {}
            ImGui::Separator();
            if (ImGui::MenuItem("Exit")) {
                glfwSetWindowShouldClose(window, GLFW_TRUE);
            }
            ImGui::EndMenu();
        }
        if (ImGui::BeginMenu("Edit")) { ImGui::EndMenu(); }
        if (ImGui::BeginMenu("View")) { ImGui::EndMenu(); }
        if (ImGui::BeginMenu("Help")) { ImGui::EndMenu(); }
        
        ImGui::EndMainMenuBar();
    }
}


void EditorUI::DrawTextEditorPane() {
    ImGuiWindowFlags flags = ImGuiWindowFlags_NoTitleBar;
    ImGui::Begin("Code Editor", nullptr, flags);

    if (ImGui::BeginTabBar("EditorTabs", ImGuiTabBarFlags_Reorderable | ImGuiTabBarFlags_AutoSelectNewTabs)) {
        
        double currentTime = ImGui::GetTime(); 

        for (auto& doc : openDocuments) {
            if (!doc.isOpen) continue;

            ImGuiTabItemFlags tabFlags = doc.isDirty ? ImGuiTabItemFlags_UnsavedDocument : ImGuiTabItemFlags_None;

            if (ImGui::BeginTabItem(doc.filename.c_str(), &doc.isOpen, tabFlags)) {
                
                doc.editor.Render(doc.filename.c_str());

                 std::string currentText = doc.editor.GetText();
        
                if (currentText != doc.lastKnownText) {
                    doc.isDirty = true; 
                    doc.lastModifiedTime = currentTime; // Reset the idle timer
                    doc.lastKnownText = currentText;    // Update the cache
                }

                ImGui::EndTabItem();
            }

            // AUTO-SAVE LOGIC
            if (doc.isDirty && (currentTime - doc.lastModifiedTime) >= 0.5) {
                
                std::ofstream outFile(doc.filepath, std::ios::trunc | std::ios::binary);
                
                if (outFile.is_open()) {
                    std::string textToSave = doc.editor.GetText();
                    outFile.write(textToSave.c_str(), textToSave.size());
                    outFile.close();
                    
                    doc.isDirty = false;
                    std::cout << "[AutoSave] " << doc.filename << " committed to disk.\n";
                } else {
                    std::cerr << "[AutoSave Error] Failed to open " << doc.filepath << " for writing.\n";
                }
            }
        }
        ImGui::EndTabBar();
    }
    ImGui::End();
}
void EditorUI::AddConsoleOutput(const std::string& text) {
    std::lock_guard<std::mutex> lock(consoleMutex);
    consoleLines.push_back(text);
    scrollToBottom = true;
}

void EditorUI::DrawConsolePane() {

    ImGuiWindowFlags flags = ImGuiWindowFlags_NoTitleBar;
    
    ImGui::Begin("Utility View", nullptr, flags);

    // Create the utility tabs (Renderer, Console, Logs)
    if (ImGui::BeginTabBar("UtilityTabs", ImGuiTabBarFlags_None)) {
        
        if (ImGui::BeginTabItem("Renderer")) {
            //later draw the OpenGL FBO texture
            ImGui::TextColored(ImVec4(0.0f, 1.0f, 0.0f, 1.0f), "[OpenGL Viewport Placeholder]");
            ImGui::EndTabItem();
        }

         if (ImGui::BeginTabItem("Console")) {
            // Create a scrollable child region inside the tab
            ImGui::BeginChild("ConsoleScrollingRegion", ImVec2(0, 0), false, ImGuiWindowFlags_HorizontalScrollbar);
            
            // lock the mutex while reading to prevent crashes if the JIT thread is printing
            std::lock_guard<std::mutex> lock(consoleMutex);
            
            for (const std::string& line : consoleLines) {
                ImGui::TextUnformatted(line.c_str()); 
            }

            // auto scroll
            if (scrollToBottom || ImGui::GetScrollY() >= ImGui::GetScrollMaxY()) {
                ImGui::SetScrollHereY(1.0f);
                scrollToBottom = false;
            }

            ImGui::EndChild();
            ImGui::EndTabItem();
        }

        if (ImGui::BeginTabItem("Logs")) {
            ImGui::Text("[INFO] FileWatcher: Detected change in source.cpp");
            ImGui::EndTabItem();
        }

        ImGui::EndTabBar();
    }

    ImGui::End();
}


void EditorUI::Render() {
    ImGui::Render();
    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

    // if viewports are enabled, update the floating windows
    ImGuiIO& io = ImGui::GetIO();
    if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable) {
        GLFWwindow* backup_current_context = glfwGetCurrentContext();
        ImGui::UpdatePlatformWindows();
        ImGui::RenderPlatformWindowsDefault();
        glfwMakeContextCurrent(backup_current_context);
    }
}

void EditorUI::Shutdown() {
    ImGui_ImplOpenGL3_Shutdown();
    ImGui_ImplGlfw_Shutdown();
    ImGui::DestroyContext();
}